import { DEFAULT_THEME_ID, THEMES, THEME_TOKENS, deriveVars } from '../../src/config/theme';

// The text of src/theme-tokens.css for the shipped default theme. Shared by the
// sync script (writes it) and the check script (compares against it).
export function renderTokensCss(): string {
  const theme = THEMES[DEFAULT_THEME_ID];
  const decl = (k: string, v: string) => `  ${k}: ${v};`;
  return [
    '/* GENERATED by scripts/sync-theme-tokens.ts from src/config/theme.ts. Do not edit by hand:',
    `   change the theme in the catalogue, then run \`npm run sync:theme\`. Default theme: ${DEFAULT_THEME_ID} (${theme.label}). */`,
    ':root {',
    ...THEME_TOKENS.map(({ key }) => decl(key, theme.vars[key])),
    '',
    '  /* Channel triplets, so `rgb(var(--ui-gold-rgb) / 0.3)` follows the theme. */',
    ...Object.entries(deriveVars(theme.vars)).map(([k, v]) => decl(k, v)),
    '',
    '  /* Derived in CSS, so they follow whatever the accent is. */',
    decl('--ui-gold-hi', 'color-mix(in srgb, var(--ui-gold), white 45%)'),
    decl('--ui-recorded-hi', 'color-mix(in srgb, var(--ui-recorded), white 45%)'),
    '}',
    '',
  ].join('\n');
}
