import type { AdminEmotion } from '../types';

function fmt(n: number): string {
  return n.toFixed(2);
}

function escape(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

export function serializeEmotions(emotions: AdminEmotion[]): string {
  const rows = emotions
    .map((e) => {
      const x = (e.x >= 0 ? ' ' : '') + fmt(e.x);
      const y = (e.y >= 0 ? ' ' : '') + fmt(e.y);
      return `  { id: '${escape(e.id)}', label: '${escape(e.label)}', x: ${x}, y: ${y}, depth: '${e.depth}', cluster: '${escape(e.cluster)}' },`;
    })
    .join('\n');

  return `// Auto-generated by admin emotion editor. Do not edit manually.
export type EmotionDepth = 'surface' | 'deep';

export interface Emotion {
  id: string;
  label: string;
  x: number;       // arousal: -1 (calm) → +1 (activated)
  y: number;       // valence: -1 (negative) → +1 (positive)
  depth: EmotionDepth;
  cluster: string;
}

export const emotions: Emotion[] = [
${rows}
];
`;
}

export function serializeDescriptions(emotions: AdminEmotion[]): string {
  const entries = emotions
    .filter((e) => e.description !== '' || e.relatedIds.length > 0)
    .map((e) => {
      const relatedStr = e.relatedIds
        .map((id) => `'${escape(id)}'`)
        .join(', ');
      return `  ${escape(e.id)}: {\n    description: '${escape(e.description)}',\n    relatedIds: [${relatedStr}],\n  },`;
    })
    .join('\n');

  return `export interface EmotionDescription {
  description: string;
  relatedIds: string[];
}

export const descriptions: Record<string, EmotionDescription> = {
${entries}
};

// Fallback for emotions without descriptions
export function getDescription(id: string): EmotionDescription {
  return descriptions[id] ?? {
    description: "A genuine feeling worth noticing.",
    relatedIds: [],
  };
}
`;
}
