import type { AdminEmotion } from '../types';

function fmt(n: number): string {
  return n.toFixed(2);
}

function escape(s: string): string {
  // Backslash and quote must be escaped; newlines/CR can't appear raw inside a
  // single-quoted TS literal, so encode them too (a multi-line description would
  // otherwise emit an unterminated string and break the generated module).
  return s
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n');
}

export function serializeEmotions(emotions: AdminEmotion[]): string {
  const rows = emotions
    .map((e) => {
      const x = (e.x >= 0 ? ' ' : '') + fmt(e.x);
      const y = (e.y >= 0 ? ' ' : '') + fmt(e.y);
      return `  { id: '${escape(e.id)}', label: '${escape(e.label)}', x: ${x}, y: ${y}, depth: '${e.depth}', cluster: '${escape(e.cluster)}' },`;
    })
    .join('\n');

  return `import type { Emotion, Framework } from './types';

// Auto-generated by the admin emotion editor. Do not edit manually.
// The hand-authored base circumplex set, exposed as a selectable framework.
const emotions: Emotion[] = [
${rows}
];

export const circumplexCustom: Framework = {
  id: 'circumplex-custom',
  name: 'Circumplex (custom)',
  emotions,
};
`;
}

export function serializeDescriptions(emotions: AdminEmotion[]): string {
  const entries = emotions
    .filter((e) => e.description !== '' || e.relatedIds.length > 0)
    .map((e) => {
      const relatedStr = e.relatedIds
        .map((id) => `'${escape(id)}'`)
        .join(', ');
      return `  '${escape(e.id)}': {\n    description: '${escape(e.description)}',\n    relatedIds: [${relatedStr}],\n  },`;
    })
    .join('\n');

  return `export interface EmotionDescription {
  description: string;
  relatedIds: string[];
}

export const descriptions: Record<string, EmotionDescription> = {
${entries}
};

// Fallback for emotions without descriptions
export function getDescription(id: string): EmotionDescription {
  return descriptions[id] ?? {
    description: "A genuine feeling worth noticing.",
    relatedIds: [],
  };
}
`;
}
